# <center>Data Types</center>

# 1. Integer

## Valid integer

In [6]:
a = 1
print(a)

1


In [7]:
type(a)

int

In [8]:
b = 123
print(b)

123


In [1]:
c = 10_105_110
print(c)

10105110


## Invalid integer

In [11]:
d = '1'
print(type(d))

<class 'str'>


Number with zero lead is not an integer.

In [12]:
01

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (3451288710.py, line 1)

## Converting other data types to integer

In [8]:
int('01')

1

In [9]:
int(1.0)

1

# 2. Floats

In [4]:
3.

3.0

In [5]:
3.0

3.0

In [6]:
3e0

3.0

In [7]:
3_000.0

3000.0

## Converting other data types to floats

In [10]:
float(1)

1.0

In [11]:
float('1')

1.0

In [12]:
float(True)

1.0

In [13]:
float(False)

0.0

# 3. Boolean

In [26]:
True

True

In [27]:
False

False

In [28]:
bool(1)

True

In [29]:
bool(0)

False

# 4. String

## String can be created using qutation marks
* 'snack'
* "snack"
* '''snack'''
* """snack"""

## Single quote can be inside double quote and vise versa

In [14]:
"'Nay!' said the naysayer. 'Neigh?' said the horse."

"'Nay!' said the naysayer. 'Neigh?' said the horse."

In [15]:
'The rare double quote in captivity: ".'

'The rare double quote in captivity: ".'

## If the same quote is used, it will produce error

In [16]:
'The rare double quote in captivity: '.'

SyntaxError: unterminated string literal (detected at line 1) (1999511489.py, line 1)

## Escape sign "\" need to be used to avoid error

In [17]:
'The rare double quote in captivity: \'.'

"The rare double quote in captivity: '."

## Triple quote is used for a long or multiple lines of string

In [18]:
poem = '''There was a Young Lady of Norway,
 Who casually sat in a doorway;
 When the door squeezed her flat,
 She exclaimed, "What of that?"
 This courageous Young Lady of Norway.'''

## Combine string

In [20]:
'Hello' + ' ' + 'world'

'Hello world'

## Duplicate string

In [21]:
'Hello ' * 5

'Hello Hello Hello Hello Hello '

## Adding something into a string

In [23]:
role = 'Accounting'

In [24]:
'My role is an {}'.format(role)

'My role is an Accounting'

In [25]:
f'My role is an {role}'

'My role is an Accounting'

# 5. List
### A collection of item or items with
* Mutability
* Order, and
* Index properties

In [30]:
a = ['hello', 'world', 12345]

## Mutability: can make a change of value of the list

In [32]:
a[2] = 'new value'

In [33]:
print(a)

['hello', 'world', 'new value']


## Order: list preserve order of data

In [35]:
[3, 2, 20, 10]

[3, 2, 20, 10]

unlike some other data types where elements is re-ordered

In [38]:
set([3, 2, 20, 10])

{2, 3, 10, 20}

## Index: list provide index so that we can call element based on its index

In [39]:
a[0]

'hello'

In [40]:
a[1]

'world'

In [41]:
a[2]

'new value'

# 6. Tuple: similar to list, but it is immutable

In [49]:
a = 'hello', 'world', 'something'

In [50]:
print(a)

('hello', 'world', 'something')


In [51]:
b = ('hello', 'world', 'something')

In [52]:
print(b)

('hello', 'world', 'something')


In [57]:
c = tuple(['hello', 'world', 'something'])

In [58]:
print(c)

('hello', 'world', 'something')


## Once created, we can't make a change on the value

In [54]:
a[2] = 'new thing'

TypeError: 'tuple' object does not support item assignment

# 7. Dictionary: similar to list, but order doesn't matter and data structure is based on key-value pairs
* Keys are unique. If same keys are provided, the latter value of the keys will overwrite previous value(s)

In [64]:
a = {
    'c': 1,
    'b': 'something',
    'a': 20,
}

In [65]:
print(a)

{'c': 1, 'b': 'something', 'a': 20}


In [70]:
b = dict(
    c = 1,
    b = 'something',
    d = 20)

In [71]:
print(b)

{'c': 1, 'b': 'something', 'd': 20}


## Call value of an item based on its key

In [73]:
a['b']

'something'

This method will product error when it can't find the selected key

In [77]:
a['not known']

KeyError: 'not known'

In [76]:
a.get('b')

'something'

This method will not product an error when it can't find the selected key

In [78]:
a.get('not known')

You can specify value when the selected key is not found

In [79]:
a.get('not known', 'some value')

'some value'

## Change value of an item

In [74]:
a['c'] = 2000

In [75]:
print(a)

{'c': 2000, 'b': 'something', 'a': 20}


## Update dictionary

In [80]:
others = { 'Marx': 'Groucho', 'Howard': 'Moe' }

In [81]:
a.update(others)

In [82]:
print(a)

{'c': 2000, 'b': 'something', 'a': 20, 'Marx': 'Groucho', 'Howard': 'Moe'}


In [84]:
{**b, **others}

{'c': 1, 'b': 'something', 'd': 20, 'Marx': 'Groucho', 'Howard': 'Moe'}

# 8. Sets: like dictionary, but only keys are kept and values are thrown away

In [85]:
a = {'this', 'is', 'set', 'set'}

In [86]:
print(a)

{'this', 'set', 'is'}


In [87]:
b = set({'c': 2000, 'b': 'something', 'a': 20, 'Marx': 'Groucho', 'Howard': 'Moe'})
print(b)

{'a', 'Marx', 'c', 'Howard', 'b'}


In [88]:
c = set([1, 1, 2, 3, 4 ])
print(c)

{1, 2, 3, 4}


## Values of Sets requires interable

In [90]:
set(123)

TypeError: 'int' object is not iterable

In [91]:
set('123')

{'1', '2', '3'}

## Add

In [93]:
a.add('something new')
print(a)

{'this', 'something new', 'set', 'is'}


## Remove

In [94]:
a.remove('something new')
print(a)

{'this', 'set', 'is'}


## Combine

In [95]:
a | b

{'Howard', 'Marx', 'a', 'b', 'c', 'is', 'set', 'this'}

# 9. N-dimensional Array with Numpy

In [1]:
import numpy as np

## One dimension array

In [2]:
a = a = np.array([0, 1, 2, 3])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[0 1 2 3]
(4,)
1
int64


## Two dimension array

In [3]:
a = a = np.array([[0, 1, 2, 3],
                           [4, 5, 6, 7]])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
2
int64


## Three dimension array

In [4]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
(3, 2, 4)
3
int64


In [5]:
a[..., 2]

array([[2, 6],
       [2, 6],
       [2, 6]])

In [9]:
a[0, ..., 2]

array([2, 6])

In [10]:
a[...]

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [12]:
a[0, :, 2]

array([2, 6])

In [18]:
[1, 2, 3, 4][1:2,..., 0]

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\admin\AppData\Local\Temp\ipykernel_7156\1448620225.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1, 2, 3, 4][1:2,..., 0]
C:\Users\admin\AppData\Local\Temp\ipykernel_7156\1448620225.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1, 2, 3, 4][1:2,..., 0]
C:\Users\admin\AppData\Local\Temp\ipykernel_7156\1448620225.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1, 2, 3, 4][1:2,..., 0]


TypeError: list indices must be integers or slices, not tuple